connection: &connection
  adapter: postgresql
  encoding: unicode
  host:     localhost
  pool: 5
  username: workshop
  password: secret

development:
  <<: *connection
  database: workshops_development

production:
  adapter: postgresql
  encoding: unicode
  database: workshops_production

test: &test
  <<: *connection
  database: workshops_test
